import React from 'react';

function Module3Content() {
  return (
    <div>
      <h3>5.1 Constructing STAR Stories from Lived Experience</h3>
      <p>The module introduces the STAR method (Situation, Task, Action, Result) not as an abstract formula to be memorized, but as a tool for structuring personal narratives. To ensure the learning is deeply connected to the participants' own histories, the first activity prompts them to return to the "Experience Inventory" they created in Module 1. They are tasked with selecting three of their "Problem-Action-Result" stories and expanding them into the full STAR format. This direct link to their prior work reinforces the learning and ensures the content is immediately relevant and personalized.</p>
      <p>To facilitate this process, the website provides a clear breakdown of the STAR components and several examples. Learners are then presented with a list of common behavioral interview questions, such as "Tell me about a time you had to solve a complex problem," or "Describe a situation where you had to work with a difficult coworker". Their task is to write out two complete, detailed STAR-based answers to questions of their choice, drawing directly from their newly structured stories.</p>

      <h3>5.2 The Virtual Mock Interview: Performance and Peer Feedback</h3>
      <p>This capstone activity is the most powerful constructivist exercise in the course. It leverages technology to create an authentic opportunity for practice and reflection. The activity instructions are as follows: "Choose one of the behavioral interview questions from the provided list. Using your smartphone or computer's webcam, record a short video (1-2 minutes) of yourself answering that question as you would in a real interview".</p>
      <p>Learners then upload their video to their small, private peer group forum. <em>[Note: This is a reflective exercise. An interactive video upload and private group forum feature will be available in a future version. For now, you can use the "Mock Interview Feedback" topic in the main <a href="/forum">Community Forum</a>.]</em> Other group members are prompted to provide constructive feedback based on a simple, focused checklist: "1. Did the speaker clearly describe the Situation and Task? 2. Did they focus on their personal Actions, using 'I' statements? 3. Was the Result specific and positive? 4. What was one thing they did very well? 5. What is one suggestion for improvement?"</p>
      <p>This process of peer review provides valuable external perspectives. However, the most profound learning often occurs through the act of self-review. When learners watch a recording of themselves, they are forced into a moment of objective self-assessment. They may notice for the first time their use of filler words like "um" or "like," nervous body language, or a tendency to ramble—behaviors they were completely unaware of while speaking. This creates a powerful metacognitive loop, a form of cognitive dissonance where their internal perception of their performance clashes with the external reality of the recording. This self-discovery is often a more potent driver of change than external feedback alone. To solidify this learning, the activity concludes with a final, private journal prompt: "After watching your own video and reading your peers' feedback, what is the single most important change you will make in your next interview?" This encourages deep reflection and promotes ownership of their own development.</p>

      <h3>5.3 The Final Step: The Art of the Follow-Up</h3>
      <p>To ensure the curriculum directly addresses all target behaviors, the module concludes with a simple but critical practical task. The prompt reads: "Based on the mock interview you just completed, draft a professional thank-you email to your 'interviewer' that you would send within 24 hours. Post your draft to the forum for a final peer check for tone and clarity." <em>[Note: Please use the "Follow-Up Email Review" topic in the <a href="/forum">Community Forum</a> for this activity.]</em> This activity provides a tangible, hands-on experience that reinforces the importance of the post-interview follow-up, transforming it from an abstract concept into a practiced skill.</p>

      <h3>5.4 Yin Integration: Managing Pre-Interview Jitters</h3>
      <p>Embedded within this high-stakes module is a practical "Yin" tool designed to help learners manage the acute anxiety that often precedes an interview. The website provides a short, easy-to-follow video demonstrating a two-minute diaphragmatic breathing exercise, a technique proven to help regulate the body's stress response. The instructions explicitly frame this not as a way to eliminate anxiety, but as a practical tool to regain a sense of composure and focus. This approach acknowledges that feeling nervous is a normal and valid response, empowering learners with a concrete strategy they can use in the moments before walking into an interview room.</p>
    </div>
  );
}

export default Module3Content;
