import React from 'react';

function Module1Content() {
  return (
    <div>
      <h3>3.1 Eliciting Prior Knowledge: The "Resume Autopsy"</h3>
      <p>The module commences by activating and honoring the learner's existing knowledge and experience, a cornerstone of constructivist teaching. The first activity, titled "The Resume Autopsy," prompts participants to upload their current resume if they have one. <em>[Note: This is a reflective exercise. Interactive functionality for uploads will be available in a future version.]</em> They are then guided through a private journaling exercise with prompts such as: "What jobs has this resume helped you get interviews for in the past?", "What feedback, positive or negative, have you received on it?", and "Looking at it now, what do you feel are its greatest strengths and weaknesses?" This process serves two critical functions. First, it respects the learner as an individual with a professional history, validating their experience as the starting point for learning. Second, it establishes a personal baseline, allowing the learner to measure their own progress and making the subsequent learning deeply relevant to their specific situation.</p>

      <h3>3.2 The Problem-Based Challenge: Deconstructing the Job Description</h3>
      <p>Rather than beginning with a passive lecture on the different sections of a resume, the module immediately immerses learners in an authentic, problem-based challenge. Participants are presented with three distinct job descriptions for roles common in the local economy (e.g., healthcare support, administrative assistant, skilled trade). Their task is to act as a hiring manager and deconstruct these descriptions, identifying and listing the essential skills, qualifications, and keywords for each role. This is an active, analytical task that requires critical thinking.</p>
      <p>After completing their individual analysis, learners post their findings to a group discussion forum. <em>[Note: The <a href="/forum">Community Forum</a> is available for these discussions. Full interactive features are under development.]</em> Here, they can compare their lists with those of their peers. The website provides guiding questions to facilitate this social learning process, such as "What patterns did you notice across the three descriptions?" and "Which keywords appeared most frequently?" Through this collaborative dialogue, the group co-constructs a shared understanding of how to "read" a job description to extract its most vital information. The facilitator's role (played by the website's prompts and structure) is to guide this discovery process, helping learners build a durable mental schema for this foundational job search skill.</p>

      <h3>3.3 The Construction Phase: Building the "Experience Inventory" and Peer Review</h3>
      <p>With a new understanding of what employers are looking for, learners move to the construction phase. They are guided through a structured brainstorming activity to create a personal "Experience Inventory." This is not simply a list of job duties but a master document of their accomplishments, framed as concise "Problem-Action-Result" stories. This inventory becomes their personal repository of "raw data" from which they can pull to build any future resume.</p>
      <p>The module then culminates in two performance-based activities. First, in the "Tailoring" Simulation, learners are tasked with a realistic challenge: "Using your Experience Inventory, create a one-page resume specifically tailored to one of the job descriptions from the previous activity." This is an authentic task that requires the application of all the concepts explored thus far.</p>
      <p>Second, learners engage in Collaborative Peer Review. They post their newly tailored resume to a small group forum and provide feedback to their peers using a simple, constructive rubric. <em>[Note: The <a href="/forum">Community Forum</a> is available for these discussions. Full interactive features are under development.]</em> The rubric focuses on key tailoring elements: "Does the professional summary directly address the needs mentioned in the job description?", "Are at least five keywords from the description present in the resume?", and "Do the bullet points quantify accomplishments where possible?". This social interaction is a critical component of constructivist learning. By seeing how others approached the same task and by articulating their own feedback, learners gain multiple perspectives, refine their own work, and co-construct a much deeper and more nuanced understanding of what constitutes an effective resume.</p>

      <h3>3.4 Yin Integration: Reflection on Professional Identity</h3>
      <p>The module concludes with a "Yin" component designed to address the emotional dimension of the resume-writing process. A job search can often feel dehumanizing, reducing a person's complex life and identity to a series of bullet points on a page. To counteract this, the final activity is a guided journal prompt: "Writing a resume requires you to focus on your professional accomplishments. Now, take a moment to reflect on a personal accomplishment you are deeply proud of that would never fit on a resume. What does this accomplishment say about your character, your values, or your resilience?" This reflective practice helps learners reconnect with their intrinsic self-worth, reinforcing the crucial idea that their value as a person is separate from and far exceeds their employment status.</p>
    </div>
  );
}

export default Module1Content;
